const express = require('express');
const levels = require('./routes/levels');
const locations = require('./routes/locations');
const location = require('./routes/location');
const questions = require('./routes/questions');
const question = require('./routes/question');
const reports = require('./routes/reports');
const report = require('./routes/report');
const users = require('./routes/users');
const user = require('./routes/user');
const auth = require('./routes/auth');
const my = require('./routes/my');
const messages = require('./routes/messages');
const expoPushTokens = require('./routes/expoPushTokens');
const helmet = require('helmet');
const compression = require('compression');
const config = require('config');
const app = express();
app.use(express.static('public'));
app.use(express.json());
app.use(helmet());
app.use(compression());

app.use('/api/levels', levels);
app.use('/api/location', location);
app.use('/api/locations', locations);
app.use('/api/question', question);
app.use('/api/questions', questions);
app.use('/api/report', report);
app.use('/api/reports', reports);
app.use('/api/user', user);
app.use('/api/users', users);
app.use('/api/auth', auth);
app.use('/api/my', my);
app.use('/api/expoPushTokens', expoPushTokens);
app.use('/api/messages', messages);
const port = process.env.PORT || config.get('port');
app.listen(port, function () {
  console.log(`Server started on port ${port}...`);
});
